### ISSUE TITLE
Final Submission

### ISSUE THREAD

**Issue by Bi-xuan** [Bi-xuan/Project_RAP#1]
@b-rodrigues
This is the final submission for Reproducible Analytical Pipeline, from Bixuan LIU.

**Comment by b-rodrigues** [comment]
Hi, very nice, the only thing I would add is the data source, and where one can also download it. Ideally, you would provide a function to download said data, but you can just indicating a download link and source, that’s fine.

**Comment by Bi-xuan** [comment]
Thank you for the note! I've updated the source of dataset in Readme.md.

**Comment by b-rodrigues** [comment]
Nice, you can close this issue then.

Just for your information, and for the future, you might want to consider writing a script that downloads the data, and then save it to be used from your pipeline. You can do so by using the provided API:

![image](https://github.com/Bi-xuan/Project_RAP/assets/2998834/18fb95a8-b60b-4cea-8b0d-8b4ee1f30e1a)

many statistical offices provide this as an option. This way, it will be much easier to update the data for future iterations of the pipeline.

**Comment by Bi-xuan** [comment]
Thanks for the very useful note!
Have a nice day!
